name: Run HumanPilot Workflow

on:
  push:
    branches:
      - main
      - dev
  pull_request:
  release:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      matrix:
        os: ['ubuntu-latest', 'windows-latest', 'macos-latest']

    steps:
      - uses: actions/checkout@v5

      - name: Install Mamba environment
        uses: mamba-org/setup-micromamba@v2
        with:
          cache-downloads: true
          cache-environment: true
          environment-file: environment.yml
          environment-name: loopy

      - name: Install ncurses if Windows
        if: matrix.os == 'windows-latest'
        run: |
          pip install windows-curses
        shell: bash -el {0}

      - name: Cache data
        uses: actions/cache@v4
        with:
          path: scripts/temp
          key: ${{ hashFiles('scripts/process_humanpilot.py') }}

      - name: Test
        run: |
          micromamba install -c conda-forge pytest pytest-cov
          pytest
        shell: bash -el {0}

      - name: Run HumanPilot data prep
        run: |
          cd scripts
          python process_humanpilot.py
        shell: bash -el {0}
